spring:
  application:
    name: device-gateway
  main:
    banner-mode: "off"

server:
  port: ${DEVICE_GATEWAY_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
