[versions]
spring-boot = "4.1.1"
spring-ai = "2.0.1"
testcontainers = "2.0.5"
paho-mqtt = "1.2.5"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "spring-ai" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
paho-mqtt-v5 = { module = "org.eclipse.paho:org.eclipse.paho.mqttv5.client", version.ref = "paho-mqtt" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
