package io.krait.fieldops.worker.telemetry;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.time.Duration;

import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.Acknowledgment;
import tools.jackson.databind.ObjectMapper;

class RedisStateProjectorTests {
    private StringRedisTemplate redis;
    private KafkaTemplate<String, String> kafka;
    private RedisStateProjector projector;

    @BeforeEach
    @SuppressWarnings("unchecked")
    void setUp() {
        JdbcClient jdbc = JdbcClient.create(new DriverManagerDataSource(
                "jdbc:h2:mem:projector-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""));
        jdbc.sql("""
                CREATE TABLE b02_device_snapshot(tenant_id VARCHAR, device_id VARCHAR, event_id VARCHAR,
                  session_id VARCHAR, session_started_at TIMESTAMP WITH TIME ZONE, sequence BIGINT,
                  payload_digest VARCHAR)
                """).update();
        jdbc.sql("""
                INSERT INTO b02_device_snapshot VALUES('tenant-a','device-a-soil-01','newer-event',
                  'newer-session', TIMESTAMP WITH TIME ZONE '2026-09-08 00:01:00+00', 5, 'sha256:newer')
                """).update();
        jdbc.sql("""
                CREATE TABLE b02_telemetry_rejection(rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                  stage VARCHAR, reason_code VARCHAR, event_id VARCHAR, tenant_id VARCHAR,
                  device_id VARCHAR, rejected_at TIMESTAMP WITH TIME ZONE)
                """).update();
        redis = mock(StringRedisTemplate.class);
        when(redis.hasKey(anyString())).thenReturn(false);
        kafka = mock(KafkaTemplate.class);
        TopicEpochProvider epochs = mock(TopicEpochProvider.class);
        when(epochs.epoch("normalized", 0)).thenReturn("epoch");
        projector = new RedisStateProjector(new ObjectMapper(), redis, kafka, jdbc, epochs,
                new SimpleMeterRegistry(), "state", Duration.ofDays(1),
                Duration.ofSeconds(15), Duration.ofSeconds(30));
    }

    @Test
    void aRedisKeyMissCannotRegressBelowThePostgresSnapshot() throws Exception {
        Acknowledgment acknowledgment = mock(Acknowledgment.class);
        String older = """
                {"eventId":"older-event","schemaVersion":"2.0.0","tenantId":"tenant-a",
                 "siteId":"site-a","deviceId":"device-a-soil-01","sessionId":"older-session",
                 "sessionStartedAt":"2026-09-08T00:00:00Z","sequence":99,
                 "observedAt":"2026-09-08T00:00:01Z","receivedAt":"2026-09-08T00:00:02Z",
                 "metrics":[{"code":"soil.moisture.pct","displayName":"Soil moisture",
                   "value":42.5,"unit":"%","quality":"GOOD","observedAt":"2026-09-08T00:00:01Z"}],
                 "payloadDigest":"sha256:older","traceId":"trace","correlationId":"older-event"}
                """;

        projector.project(new ConsumerRecord<>("normalized", 0, 10, "key", older), acknowledgment);

        verify(acknowledgment).acknowledge();
        verify(redis).hasKey(RedisStateProjector.stateKey("tenant-a", "device-a-soil-01"));
        verifyNoMoreInteractions(redis);
        verify(kafka, never()).send(anyString(), anyString(), anyString());
    }
}
