import type { Locale } from "./copy";

const ko = {
  navigation: "카메라",
  title: "카메라",
  subtitle: "현재 사이트의 실시간 영상과 제어 가능 상태를 확인합니다.",
  preview: "실시간 카메라 미리보기",
  previewUnavailable: "WebRTC 미리보기를 사용할 수 없습니다.",
  control: "PTZ 제어",
  acquire: "제어권 획득",
  release: "제어권 해제",
  available: "제어 가능",
  held: "제어 중",
  unavailable: "사용 불가",
  readOnly: "이 계정은 카메라를 조회할 수 있지만 제어 권한은 없습니다.",
  connected: "제어 연결됨",
  disconnected: "제어 연결 안 됨",
  controlLost: "제어 lease를 잃었습니다. 다시 획득해 주세요.",
  moveUp: "위로 이동",
  moveDown: "아래로 이동",
  moveLeft: "왼쪽으로 이동",
  moveRight: "오른쪽으로 이동",
  zoomIn: "확대",
  zoomOut: "축소",
  stop: "정지",
  pose: "현재 자세",
  pan: "팬",
  tilt: "틸트",
  zoom: "줌",
  motion: "동작",
  moving: "이동 중",
  idle: "정지",
  zone: "구역",
  previewState: "영상",
  controlState: "제어",
  loadFailed: "카메라 정보를 불러올 수 없습니다.",
  empty: "이 사이트에 등록된 카메라가 없습니다.",
  liveSynthetic: "Synthetic · RTSP → WebRTC",
};

const en: typeof ko = {
  navigation: "Cameras",
  title: "Cameras",
  subtitle: "View live video and control availability for the current site.",
  preview: "Live camera preview",
  previewUnavailable: "The WebRTC preview is unavailable.",
  control: "PTZ control",
  acquire: "Acquire control",
  release: "Release control",
  available: "Available",
  held: "In control",
  unavailable: "Unavailable",
  readOnly: "This account can view cameras but does not have control permission.",
  connected: "Control connected",
  disconnected: "Control disconnected",
  controlLost: "The control lease was lost. Acquire it again.",
  moveUp: "Move up",
  moveDown: "Move down",
  moveLeft: "Move left",
  moveRight: "Move right",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  stop: "Stop",
  pose: "Current pose",
  pan: "Pan",
  tilt: "Tilt",
  zoom: "Zoom",
  motion: "Motion",
  moving: "Moving",
  idle: "Idle",
  zone: "Zone",
  previewState: "Preview",
  controlState: "Control",
  loadFailed: "Could not load camera information.",
  empty: "No cameras are registered for this site.",
  liveSynthetic: "Synthetic · RTSP → WebRTC",
};

export const cameraCopy: Record<Locale, typeof ko> = { ko, en };
