CREATE TABLE b02_principal (
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (issuer, subject)
);

CREATE TABLE b02_tenant (
    tenant_id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    timezone VARCHAR(64) NOT NULL
);

CREATE TABLE b02_site (
    tenant_id VARCHAR(64) NOT NULL REFERENCES b02_tenant(tenant_id),
    site_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    PRIMARY KEY (tenant_id, site_id)
);

CREATE TABLE b02_membership (
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL REFERENCES b02_tenant(tenant_id),
    role_code VARCHAR(64) NOT NULL,
    all_sites BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    PRIMARY KEY (issuer, subject, tenant_id),
    FOREIGN KEY (issuer, subject) REFERENCES b02_principal(issuer, subject)
);

CREATE TABLE b02_membership_site (
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    site_id VARCHAR(64) NOT NULL,
    PRIMARY KEY (issuer, subject, tenant_id, site_id),
    FOREIGN KEY (issuer, subject, tenant_id) REFERENCES b02_membership(issuer, subject, tenant_id),
    FOREIGN KEY (tenant_id, site_id) REFERENCES b02_site(tenant_id, site_id)
);

CREATE TABLE b02_membership_permission (
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    permission_code VARCHAR(64) NOT NULL,
    PRIMARY KEY (issuer, subject, tenant_id, permission_code),
    FOREIGN KEY (issuer, subject, tenant_id) REFERENCES b02_membership(issuer, subject, tenant_id)
);

CREATE TABLE b02_device (
    tenant_id VARCHAR(64) NOT NULL,
    site_id VARCHAR(64) NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    external_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    type_code VARCHAR(64) NOT NULL,
    type_name VARCHAR(128) NOT NULL,
    zone_id VARCHAR(64),
    zone_name VARCHAR(128),
    protocol VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    PRIMARY KEY (tenant_id, device_id),
    UNIQUE (tenant_id, site_id, external_id),
    FOREIGN KEY (tenant_id, site_id) REFERENCES b02_site(tenant_id, site_id)
);

CREATE TABLE b02_telemetry_history (
    tenant_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    site_id VARCHAR(64) NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    session_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sequence BIGINT NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_digest VARCHAR(80) NOT NULL,
    metrics_json TEXT NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL,
    PRIMARY KEY (tenant_id, event_id),
    UNIQUE (tenant_id, device_id, session_id, sequence),
    FOREIGN KEY (tenant_id, device_id) REFERENCES b02_device(tenant_id, device_id)
);

CREATE INDEX b02_history_device_time
    ON b02_telemetry_history(tenant_id, device_id, observed_at);

CREATE TABLE b02_telemetry_rejection (
    rejection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    event_id VARCHAR(128),
    tenant_id VARCHAR(64),
    device_id VARCHAR(64),
    rejected_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE b02_device_snapshot (
    tenant_id VARCHAR(64) NOT NULL,
    site_id VARCHAR(64) NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    session_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sequence BIGINT NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload_digest VARCHAR(80) NOT NULL,
    metrics_json TEXT NOT NULL,
    state_epoch VARCHAR(255) NOT NULL,
    revision BIGINT NOT NULL,
    PRIMARY KEY (tenant_id, device_id),
    FOREIGN KEY (tenant_id, device_id) REFERENCES b02_device(tenant_id, device_id)
);

INSERT INTO b02_tenant VALUES
    ('tenant-a', 'Synthetic Farm A', 'Asia/Seoul'),
    ('tenant-b', 'Synthetic Farm B', 'Asia/Seoul');

INSERT INTO b02_site VALUES
    ('tenant-a', 'site-a', 'Greenhouse A', 'Asia/Seoul'),
    ('tenant-b', 'site-b', 'Greenhouse B', 'Asia/Seoul');

INSERT INTO b02_principal VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'Alicia Admin', 'b02-admin-a@example.invalid'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'Morgan Multi', 'b02-multi@example.invalid');

INSERT INTO b02_membership VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'TENANT_ADMIN', TRUE, 'ACTIVE'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-a', 'TENANT_VIEWER', TRUE, 'ACTIVE'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'TENANT_ADMIN', TRUE, 'ACTIVE');

INSERT INTO b02_membership_site VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'site-a'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-a', 'site-a'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'site-b');

INSERT INTO b02_membership_permission VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'OVERVIEW_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'DEVICE_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'TELEMETRY_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000a1', 'tenant-a', 'MEMBER_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-a', 'OVERVIEW_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-a', 'DEVICE_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-a', 'TELEMETRY_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'OVERVIEW_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'DEVICE_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'TELEMETRY_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000000b2', 'tenant-b', 'MEMBER_READ');

INSERT INTO b02_device VALUES
    ('tenant-a', 'site-a', 'device-a-soil-01', 'A-SOIL-01', 'A Soil Sensor 01', 'SOIL_SENSOR', 'Soil sensor', 'zone-a', 'Bed A', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1),
    ('tenant-a', 'site-a', 'device-a-soil-02', 'A-SOIL-02', 'A Soil Sensor 02', 'SOIL_SENSOR', 'Soil sensor', 'zone-a', 'Bed A', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1),
    ('tenant-a', 'site-a', 'device-a-soil-03', 'A-SOIL-03', 'A Soil Sensor 03', 'SOIL_SENSOR', 'Soil sensor', 'zone-b', 'Bed B', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1),
    ('tenant-b', 'site-b', 'device-b-soil-01', 'B-SOIL-01', 'B Soil Sensor 01', 'SOIL_SENSOR', 'Soil sensor', 'zone-a', 'Bed A', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1),
    ('tenant-b', 'site-b', 'device-b-soil-02', 'B-SOIL-02', 'B Soil Sensor 02', 'SOIL_SENSOR', 'Soil sensor', 'zone-a', 'Bed A', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1),
    ('tenant-b', 'site-b', 'device-b-soil-03', 'B-SOIL-03', 'B Soil Sensor 03', 'SOIL_SENSOR', 'Soil sensor', 'zone-b', 'Bed B', 'MQTT', '2026-09-07T00:00:00Z', '2026-09-07T00:00:00Z', 1);
