CREATE TABLE b05_command (
    command_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    site_id VARCHAR(64) NOT NULL,
    device_id VARCHAR(64) NOT NULL,
    command_type VARCHAR(16) NOT NULL CHECK (command_type IN ('OPEN', 'CLOSE')),
    scenario VARCHAR(16) NOT NULL CHECK (scenario IN ('SUCCESS', 'REJECT', 'HANG')),
    status VARCHAR(32) NOT NULL CHECK (status IN (
        'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'DISPATCHING',
        'ACKNOWLEDGED', 'SUCCEEDED', 'FAILED', 'UNKNOWN')),
    requested_by_subject VARCHAR(128) NOT NULL,
    decided_by_subject VARCHAR(128),
    idempotency_key VARCHAR(128) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    deadline_at TIMESTAMP WITH TIME ZONE NOT NULL,
    claimed_by VARCHAR(128),
    claimed_at TIMESTAMP WITH TIME ZONE,
    outcome_reason VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL,
    UNIQUE (tenant_id, requested_by_subject, idempotency_key),
    FOREIGN KEY (tenant_id, site_id) REFERENCES b02_site(tenant_id, site_id),
    FOREIGN KEY (tenant_id, device_id) REFERENCES b02_device(tenant_id, device_id)
);

CREATE INDEX b05_command_dispatch_queue
    ON b05_command(status, created_at);

CREATE TABLE b05_command_transition (
    transition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id UUID NOT NULL REFERENCES b05_command(command_id),
    sequence_no INTEGER NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    actor_subject VARCHAR(128) NOT NULL,
    reason_code VARCHAR(128),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (command_id, sequence_no)
);

CREATE TABLE b05_gateway_delivery (
    command_id UUID PRIMARY KEY,
    payload_hash CHAR(64) NOT NULL,
    command_type VARCHAR(16) NOT NULL,
    scenario VARCHAR(16) NOT NULL,
    delivery_status VARCHAR(32) NOT NULL,
    observed_state VARCHAR(16),
    actuation_count INTEGER NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO b02_principal VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'B05 Operator A', 'b05-operator-a@example.invalid'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'B05 Approver A', 'b05-approver-a@example.invalid');

INSERT INTO b02_membership VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'OPERATOR', FALSE, 'ACTIVE'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'APPROVER', FALSE, 'ACTIVE');

INSERT INTO b02_membership_site VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'site-a'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'site-a');

INSERT INTO b02_membership_permission VALUES
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'OVERVIEW_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'TELEMETRY_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'DEVICE_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a1', 'tenant-a', 'DEVICE_COMMAND_REQUEST'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'OVERVIEW_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'TELEMETRY_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'DEVICE_READ'),
    ('${oidcIssuer}', '00000000-0000-0000-0000-0000000005a2', 'tenant-a', 'DEVICE_COMMAND_APPROVE');

INSERT INTO b02_device VALUES
    ('tenant-a', 'site-a', 'valve-a-01', 'A-VALVE-01', 'Synthetic Valve A01',
     'VALVE', 'Synthetic valve', 'zone-a', 'Bed A', 'HTTP',
     '2026-09-10T00:00:00Z', '2026-09-10T00:00:00Z', 1);
